class Captions {
  constructor(client) {
    this.client = client;
  }

  async getCaptions({ videoId }) {
    if (!videoId) {
      throw new Error('Video ID is required');
    }

    const data = {
      ...this.client.getContextPayload(),
      videoId
    };

    const response = await this.client.makeRequest('player', data);
    
    if (!response || !response.captions) {
      return [];
    }

    const captionTracks = response.captions.playerCaptionsTracklistRenderer?.captionTracks || [];
    return captionTracks.map(track => ({
      baseUrl: track.baseUrl,
      name: track.name?.simpleText || 'Unknown',
      languageCode: track.languageCode,
      kind: track.kind,
      isAutoGenerated: track.kind === 'asr'
    }));
  }
}

module.exports = Captions; 